# Prometheus configuration for App Engagement Intelligence system
# Requirements: 4.1 - Performance monitoring and alerting

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # App Engagement Intelligence main application
  - job_name: 'app-engagement-intelligence'
    static_configs:
      - targets: ['app:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Node.js application metrics
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # PostgreSQL database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s