apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9091
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
      disableRecordingRules: false
      scrapeInterval: 15s
    secureJsonData: {}